---
version: 2.1

refernces:
  image_config: &image_config

    IMAGE_USERNAME: orion42   # Username on docker
    IMAGE_NAME: ubuntu-lts-r    # Name of the project on docker
    IMAGE_TAG: 0.04_devtools     #  Docker version tag
    R_LIBS: ./ci_dependencies

jobs:

  build-image:
    machine: 
      image: circleci/classic:latest
    environment:
      <<: *image_config # Import here the configuration parameters

    steps:
      - checkout

      # - *create_dir_cache_key
      # - *restore_cache_ci_dependencies
      - run: pwd
      - run: ls
      
# Preparing the Image for the Registry
# > https://circleci.com/docs/2.0/custom-images/#preparing-the-image-for-the-registry
      - run:  docker build -t $IMAGE_USERNAME/$IMAGE_NAME:$IMAGE_TAG ./
      #- run:  docker build -t $IMAGE_USERNAME/$IMAGE_NAME:$IMAGE_TAG .circleci/image/

# Pushing the image to the registry 
# > https://circleci.com/docs/2.0/custom-images/#pushing-the-image-to-the-registry
# make sure to set your Docker Hub username & password in CircleCI,
# either as project-specific environment variables  or as resources in your organization's org-global Context
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG  #&& sleep 10


  test_image:
    docker:
      - image: $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
    environment:
      <<: *image_config

    steps:
      - checkout
      - run: cat /etc/*-release # Echo Linux version
  
  check_image:
    docker:
      - image: $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
    environment:
      <<: *image_config

    steps:
      - checkout
      - run: cat /etc/*-release # Echo Linux version
      - run: apt list --upgradable
      #- run: apt list

      #- run: apt list --upgradable > deps_checksum && md5sum  deps_checksum
      - run: cur_deps_checksum=$(apt list --upgradable | md5sum) 
      - run: printf "cur = $cur_deps_checksum \n" 

      #- run: {{ checksum "deps_checksum" }}
      #- run: md5sum  deps_checksum
      # - run: rm deps_checksum  # Delete the temp file with the dir checksum
      - run:  apt-get update && apt-get upgrade -y -qq --no-install-recommends
      #- run: apt list --upgradable > deps_checksum2 && md5sum  deps_checksum2
      - run: new_deps_checksum=$(apt list --upgradable | md5sum) # && echo  $new__deps_checksum 
      - run: printf "new = $new_deps_checksum \n" 
      
      - run: |
          if [ "$new_deps_checksum" == "new_deps_checksum" ] ; then
          printf "both md5 are equals ($new_deps_checksum)\n"
          else
          printf "md5 are different!"
          printf "cur = $cur_deps_checksum \n" 
          printf "new = $new_deps_checksum \n" 
          fi

workflows:
  version: 2.1
  deploy_dockerfile:
    jobs:
      - check_image
      #- build-image
      #- test_image:
      #    requires:
      #      - build-image
 #      context: org-global
