---
version: 2.1

refernces:
  image_config: &image_config

    IMAGE_USERNAME: orion42   # Username on docker
    IMAGE_NAME: ubuntu-lts-r    # Name of the project on docker
    IMAGE_TAG: 0.04_devtools     #  Docker version tag
    R_LIBS: ./ci_dependencies

jobs:

  build-image:
    machine: 
      image: circleci/classic:latest
    environment:
      <<: *image_config # Import here the configuration parameters

    steps:
      - checkout

      # - *create_dir_cache_key
      # - *restore_cache_ci_dependencies
      - run: pwd
      - run: ls
      
# Preparing the Image for the Registry
# > https://circleci.com/docs/2.0/custom-images/#preparing-the-image-for-the-registry
      - run:  docker build -t $IMAGE_USERNAME/$IMAGE_NAME:$IMAGE_TAG ./
      #- run:  docker build -t $IMAGE_USERNAME/$IMAGE_NAME:$IMAGE_TAG .circleci/image/

# Pushing the image to the registry 
# > https://circleci.com/docs/2.0/custom-images/#pushing-the-image-to-the-registry
# make sure to set your Docker Hub username & password in CircleCI,
# either as project-specific environment variables  or as resources in your organization's org-global Context
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG  #&& sleep 10


  test_image:
    docker:
      - image: $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
    environment:
      <<: *image_config

    steps:
      - checkout
      - run: cat /etc/*-release # Echo Linux version
  
  check_image:
    docker:
      - image: $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
    environment:
      <<: *image_config

    steps:
      - checkout
      #- run: cat /etc/*-release # Echo Linux version
      #- run : md5sum --version # 8.28

      # sudo apt update 2>/dev/null | grep packages | cut -d '.' -f 1

      #https://linoxide.com/linux-how-to/list-number-packages-updates-linux/
      - run: printf "Check how many packages can be upgraded\n" && \
               apt-get -s dist-upgrade | grep "^[[:digit:]]\+ upgraded"
      - run: apt-get -s dist-upgrade | grep -Po "^[[:digit:]]+ (?=upgraded)"
      - run: pkg_num=$(apt-get -s dist-upgrade | grep -Po "^[[:digit:]]+ (?=upgraded)") && echo $pkg_num 
      - run: echo "$pkg_num to be upgraded"

      - run: |
          if [  "$pkg_num" ] ; then
            echo "$pkg_num to be upgraded - Proceed to rebuild the docker"
          else
            echo "$pkg_num to be upgraded - No further action" 
          fi

workflows:
  version: 2.1
  deploy_dockerfile:
    jobs:
      - check_image
      #- build-image
      #- test_image:
      #    requires:
      #      - build-image
 #      context: org-global
